# Generated by Django 6.0.4 on 2026-04-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamiento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="report",
            name="student_code",
        ),
        migrations.RemoveField(
            model_name="report",
            name="student_course",
        ),
        migrations.RemoveField(
            model_name="report",
            name="student_external_id",
        ),
        migrations.RemoveField(
            model_name="report",
            name="student_grade",
        ),
        migrations.RemoveField(
            model_name="report",
            name="student_name",
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="acompanamiento.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["section", "name"],
                "unique_together": {("section", "code")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(default="activo", max_length=50)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="acompanamiento.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="acompanamiento.student",
            ),
        ),
    ]
