# Generated by Django 6.0.4 on 2026-04-30 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamiento", "0002_section_remove_report_student_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={
                "ordering": ["-date_log"],
                "verbose_name": "Observación",
                "verbose_name_plural": "Observaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendation",
            options={
                "ordering": ["-date_log"],
                "verbose_name": "Recomendación",
                "verbose_name_plural": "Recomendaciones",
            },
        ),
        migrations.RenameField(
            model_name="observation",
            old_name="created_at",
            new_name="date_log",
        ),
        migrations.RenameField(
            model_name="recommendation",
            old_name="created_at",
            new_name="date_log",
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="action_required",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="responsible",
        ),
        migrations.RemoveField(
            model_name="report",
            name="description",
        ),
        migrations.RemoveField(
            model_name="report",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="section",
            name="code",
        ),
        migrations.RemoveField(
            model_name="section",
            name="description",
        ),
        migrations.RemoveField(
            model_name="student",
            name="estado",
        ),
        migrations.AddField(
            model_name="observation",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="report",
            name="academic_period",
            field=models.CharField(
                blank=True, help_text="Período académico (ej: 2026-1)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_accomplished",
            field=models.BooleanField(
                default=False, help_text="¿Se logró el objetivo?"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="objective",
            field=models.TextField(blank=True, help_text="Objetivo del acompañamiento"),
        ),
        migrations.AlterField(
            model_name="observation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("CONVIVENCIA", "Convivencia"),
                    ("ACADEMICO", "Académico"),
                    ("ESPIRITUAL", "Espiritual"),
                    ("PSICOAFECTIVO", "Psicoafectivo"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="acompanamiento.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name="course",
            name="code",
        ),
    ]
