# Generated by Django 4.2.25 on 2026-04-30 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamiento", "0003_alter_observation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="correo_institucional",
            field=models.EmailField(
                blank=True,
                help_text="Email institucional de quien registra la observación",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="correo_institucional",
            field=models.EmailField(
                blank=True,
                help_text="Email institucional de quien registra la recomendación",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="fecha_cierre",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de cierre del reporte", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="reportes/"),
        ),
        migrations.AddField(
            model_name="report",
            name="recuento",
            field=models.IntegerField(
                default=0, help_text="Número de observaciones registradas"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="grado",
            field=models.CharField(
                choices=[
                    ("PREESCOLAR", "Preescolar"),
                    ("PRIMARIA", "Primaria (4°-7°)"),
                    ("BACHILLERATO", "Bachillerato (8°-11°)"),
                ],
                default="PRIMARIA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="grado",
            field=models.CharField(
                choices=[
                    ("PREESCOLAR", "Preescolar"),
                    ("PRIMARIA", "Primaria (4°-7°)"),
                    ("BACHILLERATO", "Bachillerato (8°-11°)"),
                ],
                default="PRIMARIA",
                max_length=20,
                verbose_name="Grado/Nivel",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="estudiantes/"),
        ),
        migrations.AlterField(
            model_name="observation",
            name="content",
            field=models.TextField(help_text="Descripción de la observación"),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="content",
            field=models.TextField(help_text="Recomendación pedagógica"),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PROGRAMADO", "SEGUIMIENTO"])),
                fields=("student", "purpose"),
                name="unique_active_report_per_student_purpose",
            ),
        ),
    ]
