# Generated by Django 4.2.25 on 2026-05-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acompanamiento", "0004_observation_correo_institucional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="fin_educativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONVIVENCIA", "Convivencia"),
                    ("ACADEMICO", "Académico"),
                    ("ESPIRITUAL", "Espiritual"),
                    ("PSICOAFECTIVO", "Psicoafectivo"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="fin_educativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONVIVENCIA", "Convivencia"),
                    ("ACADEMICO", "Académico"),
                    ("ESPIRITUAL", "Espiritual"),
                    ("PSICOAFECTIVO", "Psicoafectivo"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="cumple_acompanamiento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="datos_adjuntos",
            field=models.FileField(
                blank=True, null=True, upload_to="adjuntos_reportes/"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="fines_educativos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="report",
            name="institucional_quien_atiende",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="report",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONVIVENCIA", "Convivencia"),
                    ("ACADEMICO", "Académico"),
                    ("ESPIRITUAL", "Espiritual"),
                    ("PSICOAFECTIVO", "Psicoafectivo"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Educador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("DOCENTE", "Docente"),
                            ("COORDINADOR", "Coordinador"),
                            ("ADMIN", "Administrador"),
                        ],
                        default="DOCENTE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seccion_asignada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="educadores",
                        to="acompanamiento.section",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Educador",
                "verbose_name_plural": "Educadores",
                "ordering": ["user__first_name", "user__last_name", "user__username"],
            },
        ),
    ]
