# Generated by Django 4.2.25 on 2026-05-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamiento", "0005_observation_fin_educativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="followup_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha de seguimiento registrada manualmente",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="followup_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha de seguimiento registrada manualmente",
                null=True,
            ),
        ),
    ]
