# Generated by Django 5.2.13 on 2026-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0006_observation_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educador',
            name='acceso_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educador',
            name='fines_educativos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='educador',
            name='rol',
            field=models.CharField(choices=[('ADMIN_GLOBAL', 'Admin Global'), ('ADMIN_SECCION', 'Admin de Sección')], default='ADMIN_SECCION', max_length=20),
        ),
    ]
