# Generated by Django 5.2.13 on 2026-06-05 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0007_educador_fines_acceso_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del sistema origen (Power Apps)', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(db_index=True, default=2026),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
