# Generated by Django 6.0.5 on 2026-06-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0009_educador_secciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_educativo', models.CharField(blank=True, choices=[('', 'Todos los fines'), ('ACADEMICO', 'Académico'), ('PSICOAFECTIVO', 'Psicoafectivo'), ('ESPIRITUAL', 'Espiritual'), ('CONVIVENCIA', 'Convivencia')], help_text='Vacío = todos los fines', max_length=20)),
                ('seccion', models.CharField(blank=True, choices=[('', 'Todas las secciones'), ('preescolar', 'Jardín – Tercero'), ('basica_primaria', 'Cuarto – Séptimo'), ('basica_secundaria', 'Octavo – Undécimo')], help_text='Vacío = todas las secciones', max_length=30)),
                ('scope', models.CharField(choices=[('FIN_COMPLETO', 'Todo el fin (sin importar asignación)'), ('SOLO_ASIGNADO', 'Solo donde está asignado a mí'), ('FIN_EQUIPO', 'Lo asignado a mí y a mi equipo del mismo fin')], default='FIN_COMPLETO', max_length=20)),
                ('educador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='acompanamiento.educador')),
            ],
            options={
                'verbose_name': 'Regla de permiso',
                'verbose_name_plural': 'Reglas de permiso',
                'ordering': ['educador', 'fin_educativo', 'seccion'],
            },
        ),
    ]
