# Generated by Django 5.2.13 on 2026-06-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0010_add_reglapermiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField(blank=True)),
                ('periodo', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cumple', models.BooleanField(default=False)),
                ('fecha_reapertura', models.DateTimeField(auto_now_add=True)),
                ('notas_reapertura', models.TextField(blank=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_atenciones', to=settings.AUTH_USER_MODEL)),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_reabiertos', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_atenciones', to='acompanamiento.report')),
            ],
            options={
                'verbose_name': 'Historial de atención',
                'verbose_name_plural': 'Historial de atenciones',
                'ordering': ['fecha_reapertura'],
            },
        ),
    ]
