# Generated by Django 5.2.13 on 2026-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0011_add_atencion_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID origen Power Apps', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID origen Power Apps', max_length=50),
        ),
    ]
