# Generated by Django 5.2.13 on 2026-07-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0012_add_external_id_obs_rec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CERRAR', 'Cerrar caso'), ('REABRIR', 'Reabrir caso'), ('EDITAR_REPORTE', 'Editar reporte'), ('EDITAR_OBSERVACION', 'Editar observación'), ('ELIMINAR_OBSERVACION', 'Eliminar observación'), ('EDITAR_RECOMENDACION', 'Editar recomendación'), ('ELIMINAR_RECOMENDACION', 'Eliminar recomendación')], max_length=30)),
                ('estudiante_nombre', models.CharField(blank=True, help_text='Snapshot por si el reporte se elimina', max_length=255)),
                ('detalle', models.TextField(blank=True, help_text='Contenido/estado antes del cambio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
                ('autor_original', models.ForeignKey(blank=True, help_text='Quién había creado el registro modificado o eliminado, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='acompanamiento.report')),
            ],
            options={
                'verbose_name': 'Auditoría de acción',
                'verbose_name_plural': 'Auditoría de acciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
