# Generated by Django 5.2.13 on 2026-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0013_auditoriaaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_actual', models.CharField(choices=[('Primer Periodo', 'Primer Periodo'), ('Segundo Periodo', 'Segundo Periodo'), ('Tercer Periodo', 'Tercer Periodo')], default='Tercer Periodo', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración académica',
                'verbose_name_plural': 'Configuración académica',
            },
        ),
    ]
