# Generated by Django 5.2.13 on 2026-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanamiento', '0014_configuracionacademica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Primer Periodo', 'Primer Periodo'), ('Segundo Periodo', 'Segundo Periodo'), ('Tercer Periodo', 'Tercer Periodo'), ('Cuarto Periodo', 'Cuarto Periodo')], max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionAcademica',
        ),
        migrations.AddField(
            model_name='observation',
            name='academic_period',
            field=models.CharField(blank=True, help_text='Período académico vigente al momento de registrar esta observación (evidencia histórica).', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='academic_period',
            field=models.CharField(blank=True, help_text='Período académico vigente al momento de registrar esta recomendación (evidencia histórica).', max_length=50),
        ),
    ]
