# Generated by Django 4.2.25 on 2026-04-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("grade", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
                ("section", models.CharField(blank=True, max_length=50)),
                ("estado", models.CharField(default="activo", max_length=50)),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cache de Estudiante",
                "verbose_name_plural": "Cache de Estudiantes",
                "ordering": ["full_name"],
            },
        ),
    ]
